name: TTY
pygments: true
relative_permalinks: true
google_analytics_id: UA-31255537-2
assets:
  baseurl: ./
  compress:
    css: sass
    js: uglifier
  cachebust: hard
  gzip: [ text/css, application/javascript ]
exclude: [components, Rakefile, Gemfile, Gemfile.lock]
